DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS dogs;

CREATE TABLE cats (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    cat_name TEXT NOT NULL,
    breed TEXT NOT NULL
);

CREATE TABLE dogs (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    dog_name TEXT NOT NULL,
    breed TEXT NOT NULL
);
